name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/test_fast.py

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: wineapi-yannis-1780908461
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}